{{- if or .Values.watchers.strimzi .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.nameOverride }}
  name: {{ .Values.serviceAccount.nameOverride }}
  {{- else }}
  name: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
  {{- end }}
  labels:
    {{- include "kafka-lag-exporter.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations }}
  {{- end }}
{{- end }}
