{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "kafka-lag-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secrets.data }}
  {{ .name }}: {{ .value }}
  {{- end }}
{{- end }}
