apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-lag-exporter.fullname" . }}-service
  labels:
    {{- include "kafka-lag-exporter.labels" . | nindent 4 }}
    jobLabel: {{ include "kafka-lag-exporter.fullname" . }}
    {{- if .Values.service.additionalLabels }}
{{ toYaml .Values.service.additionalLabels | indent 4 -}}
    {{- end }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-lag-exporter.selectorLabels" . | nindent 4 }}
