{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kafka-lag-exporter.fullname" . }}
  labels:
    {{- include "kafka-lag-exporter.labels" . | nindent 4 }}
    {{- if .Values.prometheusRule.additionalLabels }}
      {{- toYaml .Values.prometheusRule.additionalLabels | nindent 4 -}}
    {{- end }}
spec:
  groups:
    - name: {{ include "kafka-lag-exporter.fullname" . }}-rules
      rules:
      {{- if .Values.prometheusRule -}}
        {{- with .Values.prometheusRule }}
          {{- toYaml .rules | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
